api_platform:
  title: API Dirty Cars
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]

  collection:
    pagination:
      enabled: true
      page_parameter_name: page
      items_per_page_parameter_name: itemsPerPage
      enabled_parameter_name: enabled
      partial_parameter_name: partial
